package com.retail.auth.service;

import com.retail.auth.dto.*;
import com.retail.auth.entity.Role;
import com.retail.auth.entity.User;
import com.retail.auth.repository.UserRepository;
import com.retail.config.JwtService;
import com.retail.exception.DuplicateResourceException;
import com.retail.exception.InvalidRequestException;
import com.retail.exception.ResourceNotFoundException;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.concurrent.ConcurrentHashMap;
import java.util.Map;
import java.util.UUID;

@Service
public class AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtService jwtService;
    private final AuthenticationManager authenticationManager;

    // In-memory token store for password reset (production: use DB table with expiry)
    private final Map<String, String> resetTokens = new ConcurrentHashMap<>();

    public AuthService(UserRepository userRepository, PasswordEncoder passwordEncoder,
                       JwtService jwtService, AuthenticationManager authenticationManager) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtService = jwtService;
        this.authenticationManager = authenticationManager;
    }

    public AuthResponse register(RegisterRequest request) {
        if (userRepository.existsByEmail(request.getEmail()))
            throw new DuplicateResourceException("Email already registered: " + request.getEmail());
        User user = new User();
        user.setName(request.getName());
        user.setEmail(request.getEmail());
        user.setPassword(passwordEncoder.encode(request.getPassword()));
        user.setRole(request.getRole() != null ? request.getRole() : Role.CASHIER);
        userRepository.save(user);
        return new AuthResponse(jwtService.generateToken(user), new UserResponse(user));
    }

    public AuthResponse login(LoginRequest request) {
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(request.getEmail(), request.getPassword()));
        User user = userRepository.findByEmail(request.getEmail())
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
        return new AuthResponse(jwtService.generateToken(user), new UserResponse(user));
    }

    public UserResponse getProfile(String email) {
        return new UserResponse(userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User not found")));
    }

    /**
     * Forgot password — generates a reset token and stores it in memory.
     * In production: send token via email using JavaMailSender.
     */
    public void forgotPassword(String email) {
        // Silently succeed even if email not found (security best practice)
        userRepository.findByEmail(email).ifPresent(user -> {
            String token = UUID.randomUUID().toString();
            resetTokens.put(token, email);
            // TODO: send email with reset link containing token
            System.out.println("Password reset token for " + email + ": " + token);
        });
    }

    /** Reset password using the token generated by forgotPassword. */
    public void resetPassword(ResetPasswordRequest request) {
        String email = resetTokens.get(request.getToken());
        if (email == null)
            throw new InvalidRequestException("Invalid or expired reset token");
        User user = userRepository.findByEmail(email)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));
        user.setPassword(passwordEncoder.encode(request.getNewPassword()));
        userRepository.save(user);
        resetTokens.remove(request.getToken());
    }
}
